#######################################################################################
# Book settings
title: Curriculum Guide
author: Balaji Alwar
logo: 
description: >-
  This is a guide to building courses at UC Berkeley leveraging the Division of Data
  Sciences
url: https://balajialg.github.io/

exclude_patterns: [README.md]
only_build_toc_files: true
number_toc_chapters: true


show_sidebar: true                # Show the sidebar. Only set to false if your only wish to host a single page.
collapse_inactive_chapters: true  # Whether to collapse the inactive chapters in the sidebar


#######################################################################################
# Execution settings
execute:
  execute_notebooks: off

#######################################################################################
# HTML-specific settings
html:
  use_repository_button: true
  home_page_in_navbar: false

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate

repository:
  url: https://github.com/ds-modules/curriculum-guide
  branch: upgradebranch  # Which branch of the repository should be used when creating links

latex:
  latex_documents:
    targetname: book.tex

sphinx:
  config:
    html_theme_options:
      show_navbar_depth: 2
